name: Deploy React.js App

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Go To Frontend Directory
        run: cd MiroCode/frontend 

      - name: checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.SECRET_DOCKER_PASSWORD }} | docker login --username ${{ secrets.SECRET_DOCKER_USERNAME }} --password-stdin
          env:
            DOCKER_USERNAME: ${{ secrets.SECRET_DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.SECRET_DOCKER_PASSWORD }}

      # - name: Login in to Docker hub 
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     password: ${{ secrets.SECRET_DOCKER_USERNAME }}
      #     username: ${{ secrets.SECRET_DOCKER_PASSWORD }}

      - name: Dependencies Download
        run: npm install

      - name: I Will build in React Project
        run: npm run build

      - name: Build Docker Image
        run: docker build -t ${{ secrets.SECRET_DOCKER_USERNAME }}/react-app .

      - name: React Project Deploy on Docker Hub
        run: docker build -t ${{secrets.SECRET_DOCKER_USERNAME}}/deployreactapp .

      - name: Push docker on Docker Hub
        run: docker push ${{secrets.SECRET_DOCKER_USERNAME}}/deployreactapp

      - name: React Project run
        run: sudo systemctl reload nginx



      