name: Deploy React.js App

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        cd MiroCode/frontend
        docker build -t ${{ SECRET_DOCKER_USERNAME }}/reactapp:${{ github.sha }} .
    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ SECRET_DOCKER_PASSWORD }}" | docker login -u "${{ SECRET_DOCKER_USERNAME }}" --password-stdin
        docker push ${{ SECRET_DOCKER_USERNAME }}/reactapp:${{ github.sha }}
