name: Deploy Node.js App

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
        - name: Go to Backend Folder
          run: cd MiroCode/backend

        - name: checkout Repository
          uses: actions/checkout@v4

        - name: Setup Node.js 
          uses: actions/setup-node@v3
          with:
            node-version: 18 

        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.SECRET_DOCKER_USERNAME }} -p ${{ secrets.SECRET_DOCKER_PASSWORD }}

        - name: Dependencies Download
          run: npm install

        - name: Build Docker Image
          run: docker build -t ${{ secrets.SECRET_DOCKER_USERNAME }}/node-app .

        - name: React Project Deploy on Docker Hub
          run: docker build -t ${{secrets.SECRET_DOCKER_USERNAME}}/deploynodeapp .

        - name: Push docker on Docker Hub
          run: docker push ${{secrets.SECRET_DOCKER_USERNAME}}/deploynodeapp

        - name: React Project run
          run: sudo systemctl reload nginx